
### Theme ###
remote_theme  : chrisrhymes/bulma-clean-theme@v0.14.0
theme_color   : '#022343'


### Site settings ###
title		: Lauren Burke-McCarthy
tagline		: Databender 🌀
lang		: en
email		: laurenemilyburke17@gmail.com
description	: 
baseurl		: "" # the subpath of your site, e.g. /blog
url		: "https://laurburke.github.io"
open_new_tab	: true  

# Site Social
twitter_username : lauren_e_burke
github_username  : laurburke

# Site Logos
logo    : "assets/images/site_images/LB-round.png"
favicon : assets/images/site_images/LB-round.png


# Author Info
author:
  name      : "Lauren Burke-McCarthy"
  avatar    : "assets/images/speaking/DCC24_Speaking.JPG"
  intro     : "Hi, I'm Lauren Burke-McCarthy."
  bio       : "AI Strategy Lead | Product Data Scientist | AIGP | Responsible & Accountable AI Advocate"
  blurb     : "As a Data Scientist, I find creative solutions to complex problems."
  location  : "Columbus, OH"
  email     : laurenemilyburke17@gmail.com
  github    : laurburke
  linkedin  : lauren-e-burke
  twitter   : lauren_e_burke
  facebook  :
  instagram :
  youtube   :


### Footer ###
#footer_menu: my_footer

# Custom Footer
custom_footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/lauren_e_burke"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/lauren-e-burke"


### Analytics ###
google_analytics: UA-204825159-1



# Build settings
markdown: kramdown
#theme: minima

plugins:
  - jekyll-feed
  
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
