
# Theme
remote_theme  : chrisrhymes/bulma-clean-theme
theme_color   : '#022343'


### Site settings ###
title       : Lauren Burke 〜 Data Bender
email       : laurenemilyburke17@gmail.com
description :
baseurl     : "/v3" # the subpath of your site, e.g. /blog
url         : "/v3" # the base hostname & protocol for your site, e.g. http://example.com

# Site Social
twitter_username    : lauren_e_burke
github_username     :  laurburke

# Site Logos
logo    : "assets/images/site_images/LB-round.png"
favicon : assets/images/site_images/LB-round.png

# Author
author:
  name      : "Lauren Burke"
  avatar    : "assets/images/site_images/lauren-burke-headshot.jpeg"
  intro     : "Hi, I'm Lauren Burke."
  bio       : "Data Scientist"
  blurb     : "As a Data Scientist, I find creative solutions to complex problems."
  location  : "Columbus, OH"
  email     : laurenemilyburke17@gmail.com
  github    :
  linkedin  : lauren-e-burke
  twitter   : lauren_e_burke
  facebook  :
  instagram :
  youtube   :


# Footer
footer_menu: my_footer


# Custom Footer
custom_footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/lauren_e_burke"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/lauren-e-burke"


# Build settings
markdown: kramdown
#theme: minima

plugins:
  - jekyll-feed
  
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
